name: Build Image

on:
  pull_request:

jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Image
        uses: docker/build-push-action@v6
        with:
          context: .
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=github.com/${{ github.repository }}
          provenance: false
          tags: |
            test:latest
